### ISSUE TITLE
Feedback: Quiz feature (beta)

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#1076]
Post feedback for the quiz in here.
Include browser version and OS

**Comment by Zarthus** [comment]
- [ ] Change Icon to something more sensible, i.e. https://fontawesome.com/icons/gamepad?style=solid
- [ ] instead of setting a fixed height I'd let it automatically expand, so you don't get scrollbars. https://liefland.net/~zarthus/image/chrome_3eadffbb5e.png  https://liefland.net/~zarthus/image/chrome_2f7f9a55eef6ea07b5.png
- [ ] Display the text it is failing to match against, while also posting the result you currently have. This makes it more visual where you are going wrong (forgetting the `g` flag for instance).
- [ ] Hide the hints by default.

**Comment by Timvde** [comment]
Regarding the bug: correct markdown is `[text](url)`, not the other way around.

Improvements:
[] Keep a history (could be in localstorage if you don't want it serverside)
[] Prefill your current attempt in the editor if you navigate to there from the quiz
[] Maybe also the other way around, after writing your regex in the editor? If you're overwriting previous attempts, the history is *really* important though.

Bugs:
[] Sometimes (not consistently reproducable) the last attempt disappears when navigating away (e.g. to the editor) and back
[] Solve a task; see the new task get unlocked; submit a wrong entry for the task you just solved; navigate away and back; new task is now unavailable

Arch Linux, Firefox 64 (64 bit)

**Comment by firasdib** [comment]
# Improvements
- [ ] Show a leaderboard -- should this be on each task, or one condensed page with this info? What about privacy?
- [ ] Save regex attempt locally, in case you switch views without submitting it to the server.
- [ ] Save the best (shortest) attempt on the server (to encourage golfing) and show it when you view a task
- [ ] The quiz link should automatically return to the previous task you were visiting, not always the latest.

**Comment by Ouims** [comment]
feedback so far:
quiz 2 - test 7/8 says 'every occurence of i' or 'every I' --- I think it should go with the description and talk about 'every occurence of the word i' and there should not be a capital I there.
quiz 2 - the shortest solution is without the /i flag, but without the /i flag you're going to match all of the word "I" as well which isn't as efficient, I don't know if that's a concern but it felt wrong when it told me i didn't have the shortest solution.
note: this isn't about efficiency i guess.

quiz 6 - without @firasdib telling me what i should be doing i'd never have understand it's one key press generating two extra key, i'd suggest using that word 'extra' or finding better wording overall

**Comment by jay-tea** [comment]
I'd recommend the following fail test for task 7: "1/1/1/1"

**Comment by TWiStErRob** [comment]
Android Chrome and Chrome on Windows 10:

Intro:
- [ ] Fix grammar with: `r/\.([A-Z])/. \1/`
- [ ] Add "let's go" button to bottom (on phone you have to open the sidebar to go to next)

General:
- [ ] When I'm done with a task, there's no way to go to the next one, replace the submit button with "Next", but if the regex is edited, change it back to "Submit"
- [ ] When I press "Submit" and response is slow (the server is down or I don't have internet or it is slow) the previous error message shows up while the progress indicator is shown.
![2018-12-30_13-48-24](https://user-images.githubusercontent.com/2906988/50552952-beaa4100-0c95-11e9-9334-a937e2ebfb79.gif)
- [ ] Would it be possible to have it work offline?

Other (unrelated to quiz, but found during)
- [ ] in the explanation of `(?<![AEIOU])[A-Z]` does "Assert that the Regex below does not match" supposed to be red?

Q1
> Excellent! I guess you have some regex knowledge, so let's get started!

- [ ] I already started... also let's get started could be clickable to goto next task.

Q2
> Let's test your knowledge

- [ ] += " more"

Q3
> You can with regex return the number of matches.

- [ ] &rarr; "You can*,* with regex*,* return the number of matches."
- [ ] &rarr; "*With regex* you can *count* the number of matches."

sentence structure was strange + the it doesn't return the matches, it's not a regex feature as far as I know, but there's the API to get all the matches. Your validation script is counting the matches, not the engine, so using "return" is a bit off here. I would re-word as "count" and "match individual characters" instead of "return"

> Test 5/8: You seem to be counting vowels. A gentle reminder: aeiou are vowels.

got the above for `[A-Z]/g`
- [ ] No, I'm not counting vowels, it's sounds like I'm only doing vowels. Maybe "You seem to be counting vowels *too*." or "seem to be *including* vowels".

Q4
- [ ] again, not counting, but matching all of them

Q4 and Q5
- [ ] these feel a bit out of place, they're too easy compared to the previous ones that needed negative lookahead and understanding boundaries

Q7
`^([12]?\d{0,2})\.([12]?\d{0,2})\.([12]?\d{0,2})\.([12]?\d{1,2})$`
> Each number should be at most 255.

- [ ] This message implies a lot of things, would it be possible to help which number is not matching? I had a hard time noticing that I'm allowing 299.

- [ ] `^(\d|\d\d|1\d\d|2[0-4]\d|25[0-5])(\.(\d|\d\d|1\d\d|2[0-4]\d|25[0-5])){3}$` is accepted even though it matches:
0.0.0.00
00.0.0.0
00.00.00.00

Q8
> Test 11/15: Also remove empty tags: <>.

This is taking it a bit far, I thought we're assuming somewhat valid HTML, although it's not a biggie to add `<>|`, but a bit moot.

> Test 12/15: Tags can sometimes span multiple lines. For that reason you should also remove partial tags, which may be missing either < or > if they occur at the start or end of the string, respectively. For example, body>text</body

OK...? This is getting a bit frustrating handling edge cases that are not specified in the task. The input string `body>text</body` does *not* contain HTML tags, just a `>` and a `<` characters!

`/<\s*>|<\s*([^\s>]+).*?>((.*)<\s*\/\s*\1\s*>)?|<\s*([^\s>]+).*?\/\s*>/gs` actually handles whitespaces in all the places (note the `s` flag and the use of `\s*` all over), even where there shouldn't allow (e.g. `</` and `/>` must be without space as far as I remember, maybe in XHTML, but still), here's my test that replaces as expected, yet I get the above error:
```
<
normal-closed
>
te
xt
<
/
normal-closed
>

<
unclosed-tag
with-attribute
>

<
wrapped-self-closed
with-attribute
/
>
```

... can't proceed due to this last failure. Even after talking to Firas for a bit and realizing I don't only have to strip valid HTML, but anything that looks like it I simplified to `<[^>]*>|^[^<>]+>|<\/\w+$`, but still failing 12.

**Comment by TWiStErRob** [comment]
> `7cf2f44` Don't allow anything but letters in the tld - Firas Dib
> `f8cda54` No numbers in TLD - Firas Dib

hmm, this broke my existing accepted submission; after modifying a test case, consider re-running all the submissions and flagging the failing ones on the UI?

![image](https://user-images.githubusercontent.com/2906988/50559902-1fb43200-0cf3-11e9-924e-5a3818528810.png)

Similarly when changing requirements the originally sortest solution may not work any more, and hence it would be impossible for anyone to match the shortest solution length. Do you have anything to prevent this?

**Comment by firasdib** [comment]
@TWiStErRob No, there is nothing to prevent this. Hopefully those cases will be very limited.

**Comment by FireCubez** [comment]
General: The error messages are very vague, and so are the requirements. Having the actual unit tests that are done on the regex would be helpful

Q7
> Only digits are valid in an IP address.
My regex doesn't match non-digits, at all.

**Comment by firasdib** [comment]
@FireCubez Thanks for the feedback.

The general idea for the quiz is to not give away any solutions or intricate details, and that the user has to figure out exactly what they need to do. They need to read the task carefully and listen to the error messages. It feels more like a challenge that way, otherwise it's just a regular task. The feedback you get is meant to guide you somewhat, and is more helpful in the earlier tasks than the later.

However, if some tasks have insufficient information in the task description, or some tests are unclear, these need to be addresses.

> My regex doesn't match non-digits except for the dot separator.

If you get that error, I guarantee you're matching non-digits.

**Comment by Zarthus** [comment]
- [ ] a graph of "people who completed Q1 Q2 Q3 Q4 ..."

**Comment by firasdib** [comment]
@TWiStErRob @Zarthus Both of those graphs are, quite likely, the correct approximation. Is it any useful or fun info to share? If so, where would it be placed?

**Comment by Zarthus** [comment]
@firasdib  I'd introduce a separate menu in the very bottom with "usage statistics" to not discourage people who land in "Introduction"

**Comment by firasdib** [comment]
@Zarthus Would that be a full page with a single graph in it?

**Comment by TWiStErRob** [comment]
Agree with @Zarthus + other than the graph, in the future,
 - [ ] you could also do some nerdy stats in a table, like number of submissions tried/succeeded, fastest solution, success with most tries, time between first and last submission (could be tricky if you don't have tracking) etc.

**Comment by knoebber** [comment]
Task 9 - test 30 and 31 have same error message: "Whitespace must not be allowed in the local-part."

**Comment by firasdib** [comment]
@knoebber Thanks for the feedback. Multiple tests have similar/same messages, which is by design. Typically its not an oversight, but rather multiple tests trying to ensure you're not cheating in any way :-)

**Comment by Cosmatevs** [comment]
**Task 8**: It says "The addresses can only have a maximum value of 255 in either octet, and cannot have leading zeroes" but it accepts solutions that capture two- and three-digit numbers with leading zeroes, e.g. 01.001.01.001

**Comment by firasdib** [comment]
@Cosmatevs Do you mean task 7? We used to require not having leading zeroes, but this complicates an early task too much, and was thus removed. I'll correct the text.

**Comment by firasdib** [comment]
@Cosmatevs Since you need to match a single string in quotes, you don't need /g, as there is only one match possible. Consequently, the /m flag is unnecessary. Multi-line quotes are perfectly fine.

**Comment by Ouims** [comment]
On task 3, if you match non printable character, the regex is accepted, but these char are ascii, so it's very misleading to say 'ascii' in the description i think.
It's especially a problem if you want to find out how to get the best score 16 char.

I think the 16 char entries should be invalid with the best score being 18.

**Comment by Davidebyzero** [comment]
> On task 3, if you match non printable character, the regex is accepted, but these char are ascii, so it's very misleading to say 'ascii' in the description i think.

I would hold that the 16 char solution is valid, because the problem's input domain does not include nonprintable ASCII.

**Comment by Ouims** [comment]
yeah it does, it's possible to enter ascii char in there. I successfuly entered ascii 1, so it's possible to handle all ascii with ascii 0 being impossible to handle there.

**Comment by Davidebyzero** [comment]
> yeah it does, it's possible to enter ascii char in there. I successfuly entered ascii 1, so it's possible to handle all ascii with ascii 0 being impossible to handle there.

This only proves that a 16 character solution is valid, even if including nonprintable ASCII as you want it to.

**Comment by Davidebyzero** [comment]
> **Task 7**: It says "The addresses can only have a maximum value of 255 in either octet, and cannot have leading zeroes" but it accepts solutions that capture two- and three-digit numbers with leading zeroes, e.g. 01.001.01.001

I don't consider that to be a problem, as an IP address with leading zeroes in some of its octets is still entirely valid. For example, 127.000.000.001 acts the same as 127.0.0.1.

Also, the problem does *not* say anywhere that they cannot have leading zeros. Unless you're talking about a particular "**Test _n_/107**: ..." error message you saw?

**Comment by Davidebyzero** [comment]
On task 23, a regex that changes `]*` to `]`, or `]*c*d[*asdf**]a*f*[sf*f*s` to `]cd[asdf]a*f*[sffs`, or for that matter erases the `*`s between the first `]` and the first `[` in any string starting with `]`, incorrectly succeeds. I temporarily had such an invalid solution as I was golfing down my solution. (Now it's valid, and even shorter.)

**Comment by firasdib** [comment]
> > **Task 7**: It says "The addresses can only have a maximum value of 255 in either octet, and cannot have leading zeroes" but it accepts solutions that capture two- and three-digit numbers with leading zeroes, e.g. 01.001.01.001
> 
> I don't consider that to be a problem, as an IP address with leading zeroes in some of its octets is still entirely valid. For example, 127.000.000.001 acts the same as 127.0.0.1.
> 
> Also, the problem does _not_ say anywhere that they cannot have leading zeros. Unless you're talking about a particular "**Test _n_/107**: ..." error message you saw?

Initially the task disallowed leading zeros. But I thought this ruined the general experience of this early task and complicated more than necessary, and decided to remove it. Some remnants of it remained, but it has been leaned up now.

> On task 23, a regex that changes ]* to ], or ]*c*d[*asdf**]a*f*[sf*f*s to ]cd[asdf]a*f*[sffs, or for that matter erases the *s between the first ] and the first [ in any string starting with ], incorrectly succeeds. I temporarily had such an invalid solution as I was golfing down my solution. (Now it's valid, and even shorter.)

Thanks. I'll fix.

**Comment by firasdib** [comment]
I'm considering deleting the email task, as I do not believe it adds anything of value to the quiz, and is just "more of the same". Thoughts?

**Comment by jay-tea** [comment]
> I'm considering deleting the email task, as I do not believe it adds anything of value to the quiz, and is just "more of the same". Thoughts?

I'd say it's one of the more interesting ones to shorten, but I'm biased :)

**Comment by firasdib** [comment]
> I'd say it's one of the more interesting ones to shorten, but I'm biased :)

Most of the solutions allow for quite invalid input. The testing isn't far as extensive as it has to be. If I make it stricter, that'll also make it more boring.

Unsure.

**Comment by knoebber** [comment]
> I'm considering deleting the email task, as I do not believe it adds anything of value to the quiz, and is just "more of the same". Thoughts?

I had a lot fun doing that one and learned a lot. I understand that most of our solutions are far away from recognizing all valid emails, but I still think its a valuable exercise.

**Comment by firasdib** [comment]
Okay, in that case I could add a few more tests to root out the obviously invalid emails, and keep the task.

**Comment by Cosmatevs** [comment]
Clicking the submit button should force checking if the expression has been changed.
![clip0018](https://user-images.githubusercontent.com/44393502/50845480-41558f00-136d-11e9-9bc5-b8d8026e9f94.gif)

**Comment by firasdib** [comment]
This issue is getting hard to track, so if you don't mind, would you please open specific issues using the new Quiz Template, so that I can get a better idea of what needs fixing?

Thanks for all the reports guys.
